name: Go

on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - .github/workflows/go.yaml
  pull_request:
    branches:
      - master
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - .github/workflows/go.yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.13.8'
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build Go build environment image
        run: |
          docker build \
            --tag go-build-env \
            --target gobuild .
      - name: Vet code
        run: |
          docker run \
            --workdir /go/src/github.com/keep-network/keep-ecdsa \
            go-build-env \
            go vet ./.../
      - name: Check formatting
        run: |
          docker run \
            --workdir /go/src/github.com/keep-network/keep-ecdsa \
            go-build-env \
            'go get -u golang.org/x/tools/cmd/goimports && '\
            'goimports -l -w **/*.go'
      - name: Lint code
        run: |
          docker run \
            --workdir /go/src/github.com/keep-network/keep-ecdsa \
            go-build-env \
            'go get -u golang.org/x/lint/golint && '\
            'golint ./.../'
